import { describe, it, expect } from "vitest";
import {
  NARRATION_STYLES,
  VOICES,
  availableVoices,
  defaultNarrationForGrade,
  gradeLevel,
  narrationStyleHint,
  narrationStyles,
  voiceLabel,
} from "../narration";
import en from "@/i18n/messages/en.json";

describe("gradeLevel — parse a free-text grade label to a level", () => {
  it("reads plain grade/year/primary numbers", () => {
    expect(gradeLevel("Grade 1")).toBe(1);
    expect(gradeLevel("Grade 4")).toBe(4);
    expect(gradeLevel("Year 7")).toBe(7);
    expect(gradeLevel("Primary 3")).toBe(3);
    expect(gradeLevel("Tahun 2")).toBe(2); // Malay primary
  });
  it("maps secondary systems ABOVE primary", () => {
    expect(gradeLevel("Form 1")).toBe(7); // Form 1 ≈ grade 7
    expect(gradeLevel("Tingkatan 1")).toBe(7); // Malay secondary
    expect(gradeLevel("Secondary 2")).toBe(8);
  });
  it("kindergarten / pre-school is below grade 1", () => {
    expect(gradeLevel("Kindergarten")).toBe(0);
    expect(gradeLevel("Tadika")).toBe(0);
    expect(gradeLevel("Pre-school")).toBe(0);
  });
  it("takes the first number of a range", () => {
    expect(gradeLevel("6th-8th Grade")).toBe(6);
  });
  it("returns null when there's nothing to parse", () => {
    expect(gradeLevel(null)).toBeNull();
    expect(gradeLevel("")).toBeNull();
    expect(gradeLevel("General")).toBeNull();
  });
});

describe("defaultNarrationForGrade — age-appropriate narration", () => {
  it("grades 1–4 (and kindergarten) default to Storytelling", () => {
    for (const g of ["Kindergarten", "Grade 1", "Year 2", "Tahun 3", "Primary 4"]) {
      expect(defaultNarrationForGrade(g)).toBe("storytelling");
    }
  });
  it("grades 5–9 (incl. lower secondary) keep Socratic", () => {
    for (const g of ["Grade 5", "Year 7", "Grade 9", "Form 1", "Tingkatan 3"]) {
      expect(defaultNarrationForGrade(g)).toBe("socratic");
    }
  });
  it("grade 10 onwards (incl. upper secondary) defaults to Conversational", () => {
    for (const g of ["Grade 10", "10th Grade", "Year 11", "Form 4", "Tingkatan 5", "Grade 12"]) {
      expect(defaultNarrationForGrade(g)).toBe("conversational");
    }
  });
  it("an unknown/blank grade keeps the global default (Socratic)", () => {
    expect(defaultNarrationForGrade(null)).toBe("socratic");
    expect(defaultNarrationForGrade("General")).toBe("socratic");
  });
});

// The pickers: the WORDS come from the dictionary, the VALUES are the contract
// the worker reads out of `generations.params`. Translating one must never move
// the other — a lesson generated by an Arabic-reading teacher still posts
// "socratic" and "edge-zariyah".
const T = en.utils.narration;

describe("narration + voice pickers", () => {
  it("every id in the registry has a word in the dictionary", () => {
    for (const style of NARRATION_STYLES) {
      expect(T.styles[style]).toBeTruthy();
      expect(T.styleHints[style]).toBeTruthy();
    }
    for (const voice of VOICES) expect(T.voices[voice.value]).toBeTruthy();
  });

  it("translates the labels and leaves the stored ids alone", () => {
    const ar = {
      styles: { ...T.styles, socratic: "سقراطي" },
      styleHints: { ...T.styleHints, socratic: "يقود الطلاب إلى اكتشاف الأفكار بالأسئلة." },
      voices: { ...T.voices, "edge-zariyah": "زارية — العربية" },
    };
    expect(narrationStyles(ar)[0]).toEqual({
      value: "socratic",
      label: "سقراطي",
      desc: "يقود الطلاب إلى اكتشاف الأفكار بالأسئلة.",
    });
    expect(narrationStyles(ar).map((s) => s.value)).toEqual([...NARRATION_STYLES]);
    expect(narrationStyleHint(ar, "socratic")).toBe("يقود الطلاب إلى اكتشاف الأفكار بالأسئلة.");
    expect(voiceLabel(ar, "edge-zariyah")).toBe("زارية — العربية");
  });

  it("offers the lesson language's voices (Jawi borrows Malay's)", () => {
    expect(availableVoices(T, "ar").map((v) => v.value)).toEqual(["edge-zariyah", "edge-hamed"]);
    expect(availableVoices(T, "ms-arab").map((v) => v.value)).toEqual(["edge-yasmin", "edge-osman"]);
    expect(availableVoices(T, null)).toHaveLength(VOICES.filter((v) => v.tier === "free").length);
  });

  it("an id the dictionary no longer knows shows as itself, never blank", () => {
    expect(voiceLabel(T, "edge-retired")).toBe("edge-retired");
    expect(narrationStyleHint(T, "retired_style")).toBe("");
  });
});
