import { afterEach, beforeEach, describe, it, expect, vi } from "vitest";
import {
  AUTO_VOICE,
  NARRATION_STYLES,
  PAID_VOICE_TIERS,
  VOICES,
  availableVoices,
  defaultNarrationForGrade,
  defaultPresentationParams,
  defaultVoiceFor,
  expectedVoiceFor,
  gradeLevel,
  narrationStyleHint,
  narrationStyles,
  premiumProvider,
  premiumVoicesFor,
  providerOf,
  voiceLabel,
} from "../narration";
import en from "@/i18n/messages/en.json";

describe("gradeLevel — parse a free-text grade label to a level", () => {
  it("reads plain grade/year/primary numbers", () => {
    expect(gradeLevel("Grade 1")).toBe(1);
    expect(gradeLevel("Grade 4")).toBe(4);
    expect(gradeLevel("Year 7")).toBe(7);
    expect(gradeLevel("Primary 3")).toBe(3);
    expect(gradeLevel("Tahun 2")).toBe(2); // Malay primary
  });
  it("maps secondary systems ABOVE primary", () => {
    expect(gradeLevel("Form 1")).toBe(7); // Form 1 ≈ grade 7
    expect(gradeLevel("Tingkatan 1")).toBe(7); // Malay secondary
    expect(gradeLevel("Secondary 2")).toBe(8);
  });
  it("kindergarten / pre-school is below grade 1", () => {
    expect(gradeLevel("Kindergarten")).toBe(0);
    expect(gradeLevel("Tadika")).toBe(0);
    expect(gradeLevel("Pre-school")).toBe(0);
  });
  it("takes the first number of a range", () => {
    expect(gradeLevel("6th-8th Grade")).toBe(6);
  });
  it("returns null when there's nothing to parse", () => {
    expect(gradeLevel(null)).toBeNull();
    expect(gradeLevel("")).toBeNull();
    expect(gradeLevel("General")).toBeNull();
  });
});

describe("defaultNarrationForGrade — age-appropriate narration", () => {
  it("grades 1–4 (and kindergarten) default to Storytelling", () => {
    for (const g of ["Kindergarten", "Grade 1", "Year 2", "Tahun 3", "Primary 4"]) {
      expect(defaultNarrationForGrade(g)).toBe("storytelling");
    }
  });
  it("grades 5–9 (incl. lower secondary) keep Socratic", () => {
    for (const g of ["Grade 5", "Year 7", "Grade 9", "Form 1", "Tingkatan 3"]) {
      expect(defaultNarrationForGrade(g)).toBe("socratic");
    }
  });
  it("grade 10 onwards (incl. upper secondary) defaults to Conversational", () => {
    for (const g of ["Grade 10", "10th Grade", "Year 11", "Form 4", "Tingkatan 5", "Grade 12"]) {
      expect(defaultNarrationForGrade(g)).toBe("conversational");
    }
  });
  it("an unknown/blank grade keeps the global default (Socratic)", () => {
    expect(defaultNarrationForGrade(null)).toBe("socratic");
    expect(defaultNarrationForGrade("General")).toBe("socratic");
  });
});

// The pickers: the WORDS come from the dictionary, the VALUES are the contract
// the worker reads out of `generations.params`. Translating one must never move
// the other — a lesson generated by an Arabic-reading teacher still posts
// "socratic" and "edge-zariyah".
const T = en.utils.narration;

describe("narration + voice pickers", () => {
  it("every id in the registry has a word in the dictionary", () => {
    for (const style of NARRATION_STYLES) {
      expect(T.styles[style]).toBeTruthy();
      expect(T.styleHints[style]).toBeTruthy();
    }
    for (const voice of VOICES) expect(T.voices[voice.value]).toBeTruthy();
  });

  it("translates the labels and leaves the stored ids alone", () => {
    const ar = {
      styles: { ...T.styles, socratic: "سقراطي" },
      styleHints: { ...T.styleHints, socratic: "يقود الطلاب إلى اكتشاف الأفكار بالأسئلة." },
      voices: { ...T.voices, "edge-zariyah": "زارية — العربية" },
    };
    expect(narrationStyles(ar)[0]).toEqual({
      value: "socratic",
      label: "سقراطي",
      desc: "يقود الطلاب إلى اكتشاف الأفكار بالأسئلة.",
    });
    expect(narrationStyles(ar).map((s) => s.value)).toEqual([...NARRATION_STYLES]);
    expect(narrationStyleHint(ar, "socratic")).toBe("يقود الطلاب إلى اكتشاف الأفكار بالأسئلة.");
    expect(voiceLabel(ar, "edge-zariyah")).toBe("زارية — العربية");
  });

  it("offers Automatic first, then the lesson language's voices (Jawi borrows Malay's)", () => {
    expect(availableVoices(T, "ar").map((v) => v.value)).toEqual(["auto", "edge-zariyah", "edge-hamed"]);
    expect(availableVoices(T, "ms-arab").map((v) => v.value)).toEqual(["auto", "edge-yasmin", "edge-osman"]);
    expect(availableVoices(T, null)).toHaveLength(VOICES.filter((v) => v.tier === "free").length);
  });

  it("the untouched picker sends `auto`, never a frozen concrete default", () => {
    expect(AUTO_VOICE).toBe("auto");
    expect(defaultPresentationParams(null).tts_voice).toBe("auto");
    expect(defaultPresentationParams("ms").tts_voice).toBe("auto");
    // The free default still exists — it is what `auto` renders as on a free plan.
    expect(defaultVoiceFor("ms-arab")).toBe("edge-yasmin");
  });

  it("an id the dictionary no longer knows shows as itself, never blank", () => {
    expect(voiceLabel(T, "edge-retired")).toBe("edge-retired");
    expect(narrationStyleHint(T, "retired_style")).toBe("");
  });
});

// Premium voices follow the PLAN (my_fair_use) and the deployment's active
// provider — mirroring the worker's gate, which has the last word anyway.
describe("premium voices — plan and provider", () => {
  // the legacy assertions must not depend on the ambient shell (a dev
  // machine's .env.local may carry the provider variable)
  beforeEach(() => {
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "");
    vi.stubEnv("NEXT_PUBLIC_ELEVENLABS_ENABLED", "");
  });
  afterEach(() => vi.unstubAllEnvs());
  const paid = { premium: true };

  // 0105 moved the decision into the database (premium_voices_allowed: a paid
  // tier, or a comp override of 100000+). What this case now pins is the
  // FALLBACK the app uses when my_fair_use() carries no `premium_voices` key —
  // an un-migrated database, i.e. the window between deploy and migration.
  // The full truth table lives in premium-voice-gate.test.ts, shared with the
  // worker.
  it("with no answer from the database, the paid allow-list decides — and only it", () => {
    expect([...PAID_VOICE_TIERS].sort()).toEqual(["family", "homeschool", "pro", "pro_plus", "school"]);
    for (const tier of ["pro", "pro_plus", "family", "homeschool", "school"]) {
      expect(premiumVoicesFor({ tier })).toBe(true);
    }
    for (const tier of ["trial", "promo", "school_trial", "school_expired", "legacy", ""]) {
      expect(premiumVoicesFor({ tier })).toBe(false);
    }
    // WAS `true` before 0105, and that was the bug: `unlimited` is set by a
    // comp override of ANY size, so 11 seeded 20-book accounts counted as paid.
    // The fallback must never reach back to it.
    expect(premiumVoicesFor({ tier: "unlimited", unlimited: true })).toBe(false);
    expect(premiumVoicesFor(null)).toBe(false);
    expect(premiumVoicesFor(undefined)).toBe(false);
  });

  it("the database's answer, when present, is the answer", () => {
    expect(premiumVoicesFor({ tier: "unlimited", unlimited: true, premium_voices: true })).toBe(true);
    expect(premiumVoicesFor({ tier: "unlimited", unlimited: true, premium_voices: false })).toBe(false);
    expect(premiumVoicesFor({ tier: "pro", premium_voices: false })).toBe(false);
  });

  it("families come from the id prefix, like the worker's registry", () => {
    expect(providerOf("edge-aria")).toBe("edge");
    expect(providerOf("el-rachel")).toBe("elevenlabs");
    expect(providerOf("g-ar-f")).toBe("google");
    expect(providerOf("auto")).toBe("edge");
  });

  it("unset or unknown provider is legacy — nothing premium is shown, as today", () => {
    expect(premiumProvider()).toBe("legacy");
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "openai");
    expect(premiumProvider()).toBe("legacy");
    expect(availableVoices(T, "ar", paid).every((v) => v.tier === "free")).toBe(true);
  });

  it("a free account never sees premium voices, whatever the provider", () => {
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "google");
    vi.stubEnv("NEXT_PUBLIC_ELEVENLABS_ENABLED", "true");
    expect(availableVoices(T, "ar").every((v) => v.tier === "free")).toBe(true);
    expect(availableVoices(T, "ar", { premium: false }).every((v) => v.tier === "free")).toBe(true);
  });

  it("google: a paid account sees the language's Google pair, not other languages'", () => {
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "google");
    expect(availableVoices(T, "ar", paid).map((v) => v.value)).toEqual([
      "auto", "edge-zariyah", "edge-hamed", "g-ar-f", "g-ar-m",
    ]);
    expect(availableVoices(T, "ms-arab", paid).map((v) => v.value)).toEqual([
      "auto", "edge-yasmin", "edge-osman", "g-ms-f", "g-ms-m",
    ]);
    const en = availableVoices(T, "en", paid).map((v) => v.value);
    expect(en).toContain("g-en-f");
    expect(en).toContain("g-en-in-m");
    expect(en).not.toContain("el-rachel"); // legacy flag off
  });

  it("the legacy ElevenLabs flag keeps el-* pickable for paid accounts in every mode", () => {
    vi.stubEnv("NEXT_PUBLIC_ELEVENLABS_ENABLED", "true");
    expect(availableVoices(T, "ar", paid).map((v) => v.value)).toEqual([
      "auto", "edge-zariyah", "edge-hamed", "el-rachel", "el-adam",
    ]);
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "google");
    const both = availableVoices(T, "ar", paid).map((v) => v.value);
    expect(both).toEqual(["auto", "edge-zariyah", "edge-hamed", "el-rachel", "el-adam", "g-ar-f", "g-ar-m"]);
  });

  it("elevenlabs mode: a paid account sees el-* even with the legacy flag off", () => {
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "elevenlabs");
    expect(availableVoices(T, "ar", paid).map((v) => v.value)).toEqual([
      "auto", "edge-zariyah", "edge-hamed", "el-rachel", "el-adam",
    ]);
    expect(availableVoices(T, "ar").map((v) => v.value)).toEqual(["auto", "edge-zariyah", "edge-hamed"]);
  });

  it("every Google entry has a label that names its gender, since star names carry no cue", () => {
    for (const v of VOICES.filter((v) => providerOf(v.value) === "google")) {
      const label = T.voices[v.value];
      expect(label, v.value).toMatch(v.value.endsWith("-f") ? /female/ : /(^|[^e])male/);
    }
  });
});

describe("expectedVoiceFor — what `auto` will render as", () => {
  beforeEach(() => vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", ""));
  afterEach(() => vi.unstubAllEnvs());

  it("legacy or free: the language's free voice (today's behaviour)", () => {
    expect(expectedVoiceFor("ar", false)).toBe("edge-zariyah");
    expect(expectedVoiceFor("ar", true)).toBe("edge-zariyah"); // legacy
    expect(expectedVoiceFor(null, true)).toBe("edge-aria");
  });

  it("google + paid: the female Chirp voice for the language, WaveNet A for Malay", () => {
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "google");
    expect(expectedVoiceFor("ar", true)).toBe("g-ar-f");
    expect(expectedVoiceFor("en", true)).toBe("g-en-f");
    expect(expectedVoiceFor("ms-arab", true)).toBe("g-ms-f");
    expect(expectedVoiceFor("ar", false)).toBe("edge-zariyah"); // still free for a free plan
  });

  it("a language with no Google entry falls to defaultVoiceFor — the global default when the language has no free voice either", () => {
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "google");
    expect(expectedVoiceFor("zh", true)).toBe(defaultVoiceFor("zh"));
    expect(expectedVoiceFor("zh", true)).toBe("edge-aria");
  });

  it("elevenlabs + paid: the multilingual Rachel, whatever the language", () => {
    vi.stubEnv("NEXT_PUBLIC_TTS_PREMIUM_PROVIDER", "elevenlabs");
    expect(expectedVoiceFor("hi", true)).toBe("el-rachel");
  });
});
