import { AUTO_VOICE, DEFAULT_STYLE, defaultNarrationForGrade } from "./narration";

// When is a colleague's kit the SAME kit?
//
// Generation is the expensive step — a full kit is six artifacts and roughly
// 56 minutes of worker time — and five teachers of the same form generating
// the same chapter is that cost five times over for near-identical output.
// Book dedup saves an indexing run; this saves the whole generation.
//
// But only when the output really would be interchangeable. A kit carries the
// teacher's choices: narration style, language, voice, difficulty. Offering
// Sara's Socratic English lesson to a teacher who asked for storytelling in
// Malay is not a saving, it is a wrong answer. So two kits match only when
// every choice that reaches the worker agrees.
//
// The defaults are what make this fire at all. `defaultNarrationForGrade`
// derives the style from the BOOK'S grade, so two teachers who both leave it
// alone land on the same value — the default is a property of the book, not of
// whoever clicked. In the live data ~76% of generations take it.

/** The choices that change what the worker produces. */
export type KitParams = Record<string, unknown>;

/** One side of a comparison: a finished kit, or the kit a click would queue. */
export type KitRef = {
  kind: string;
  chapterRef: string | null;
  params: KitParams | null;
  grade: string | null;
  /** What an unset / `auto` voice is expected to RENDER as for this
   *  account (narration.expectedVoiceFor) — a paid school's premium default
   *  must not match a colleague's free-voice kit. Omitted = no prediction,
   *  and two unset requests still compare equal. */
  defaultVoice?: string | null;
};

const str = (v: unknown): string | null =>
  typeof v === "string" && v.trim() !== "" ? v.trim().toLowerCase() : null;

const num = (v: unknown): number | null => {
  const n = typeof v === "number" ? v : typeof v === "string" ? Number(v) : NaN;
  return Number.isFinite(n) ? n : null;
};

/** A voice the teacher actually chose. `auto` (and the older absent value)
 *  mean "whatever the worker picks", which is not a choice. */
const chosenVoice = (v: unknown): string | null => {
  const s = str(v);
  return s && s !== AUTO_VOICE ? s : null;
};

/** The voice a finished kit RENDERED with — the worker records it after
 *  synthesis as `tts_voice_used` (a string; tolerate a list). */
const renderedVoice = (p: KitParams): string | null => {
  const u = p.tts_voice_used;
  return Array.isArray(u) ? str(u[0]) : str(u);
};

/**
 * A stable signature for "would the worker produce the same thing?".
 *
 * Defaults are RESOLVED first, so a kit generated before a picker existed and
 * one generated by explicitly choosing the same value compare equal — the
 * stored params differ, the output does not.
 *
 * `grade` is the book's, and only used to resolve the narration default.
 */
export function kitSignature(opts: KitRef): string {
  const p = opts.params ?? {};
  // Two spellings exist in the wild — the picker writes narration_style, some
  // older rows carry narrationStyle.
  const narration = str(p.narration_style) ?? str(p.narrationStyle) ?? defaultNarrationForGrade(opts.grade) ?? DEFAULT_STYLE;
  // Language defaults to the book's own detected language, which is the same
  // for everyone reading it, so an unset value is simply "the book's".
  const language = str(p.language) ?? "(book)";
  // Voice only reaches audio. A doc kit has none, so it must not split docs
  // that are otherwise identical. The EFFECTIVE voice is what counts
  // (founder, 2026-09-03): what a finished kit rendered with wins over what
  // was asked; an unset / `auto` request resolves to the caller's prediction
  // of the default, so two untouched requests on the same plan still match
  // and a premium default never matches a free-voice kit.
  const voice =
    opts.kind === "presentation"
      ? (renderedVoice(p) ??
        chosenVoice(p.tts_voice) ??
        chosenVoice(p.ttsVoice) ??
        str(opts.defaultVoice) ??
        "(default)")
      : "(n/a)";
  // Difficulty only exists on the assessment kinds.
  const difficulty = str(p.difficulty) ?? "(n/a)";
  const part = num(p.part) ?? 0;

  return [opts.kind, opts.chapterRef ?? "", part, narration, language, voice, difficulty].join("|");
}

/** Would this existing kit serve a teacher asking for `wanted`? */
export function kitsInterchangeable(a: KitRef, b: KitRef): boolean {
  return kitSignature(a) === kitSignature(b);
}
