-- 0030 — Reset the AI-Tutor board state after the render/prompt quality fix.
--
-- The first board build shipped three defects (reported 2026-07-10): long labels
-- overflowed the canvas, multiple labels stacked on one point, and the model drew
-- empty placeholder rectangles instead of real catalog objects. The renderer +
-- interpreter fixes cure the overflow/stacking for ANY scene graph, but two pieces
-- of state were produced UNDER THE OLD prompt and must be discarded so they can be
-- regenerated cleanly:
--   * tutor_tal_cache — every cached TAL program was generated by the pre-fix
--     gateway prompt (no label-length / catalog-preference / spread rules) and the
--     "empty rectangle" shape is baked into the TAL itself — no render fix helps a
--     cached program. Clear it ALL; it rewarms at ~$0.001 per turn.
--   * tutor_board / tutor_board_event — persisted boards already hold the applied
--     bad turns (empty prim.rects, overflowing text). A resumed session replays
--     them. Reset each board to empty so the next student question rebuilds it with
--     the improved prompt + the new bio.plant_cell object.
--
-- Boards are ephemeral teaching surfaces (not records of account/work), so a reset
-- is non-destructive: the student simply asks again and gets a better board.
-- Idempotent; safe to run once. RLS is bypassed by the service role running it.

begin;

-- 1) Drop all cached TAL (regenerated on demand under the new prompt).
truncate table public.tutor_tal_cache;

-- 2) Drop the per-board event logs, then blank the boards back to turn 0.
truncate table public.tutor_board_event;

update public.tutor_board
set scene_graph = '{"scene":"board","nodes":[]}'::jsonb,
    board_hash  = '',
    turn        = 0,
    event_seq   = 0,
    updated_at  = now();

commit;
